version: '3'

services:
  dmoj:
    container_name: dmoj
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./problems:/opt/problems
      - ./db:/var/lib/mysql
