version: '3'

services:
  dmoj:
    container_name: dmoj
    build:
      context: web
    ports:
      - 8000:8000
      - 9999:9999
      - 9998:9998
      - 15100:15100
      - 15101:15101
      - 15102:15102
    volumes:
      - problems:/opt/problems
    depends_on:
      - dmoj_db
    healthcheck:
      test: ["CMD", "curl", "-f", "dmoj_db:3306"]
      interval: 30s
      timeout: 10s
      retries: 10

  dmoj_db:
    container_name: dmoj_db
    image: mariadb:latest
    env_file:
      - .env_db
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  dmoj_judge:
    container_name: dmoj_judge
    build:
      context: judge
    volumes:
      - problems:/problems
    env_file:
      - .env_judge
    command: bash -c "python dmoj -c /judge/config/judge.yml ${SERVER_HOST} ${JUDGE_NAME} ${JUDGE_KEY}"

volumes:
  problems:
