version: '3'

services:
  dmoj:
    container_name: dmoj
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
      - 9999:9999
      - 9998:9998
      - 15100:15100
      - 15101:15101
      - 15102:15102
    volumes:
      - ./problems:/opt/problems
    networks:
      - dmoj_network

  dmoj_db:
    container_name: dmoj_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: test
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: qwerty
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
    - dmoj_network


networks:
    dmoj_network:
